import ReactQueryProvider from "@/context/ReactQueryProvider";
import Header from "@/Components/Header";
import Sidebar from "@/Components/Header/Sidebar";
import Footer from "@/Components/Footer";
import type { Metadata } from "next";
import "../globals.css";
import { FaWhatsapp } from "react-icons/fa";
import { ToastContainer } from "react-toastify";
import "@/i18n";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
          {`
            @keyframes jump {
              0%, 100% {
                transform: translateY(0);
              }
              50% {
                transform: translateY(-10px);
              }
            }
          `}
        </style>
      </head>
      <body className="relative">
        <ReactQueryProvider>
          <ToastContainer position="top-right" autoClose={3000} />
          <Header />

          <div>
            <Sidebar />
            <div>{children}</div>
          </div>
          <Footer />

          <a
            href="https://wa.me/your-number"
            target="_blank"
            rel="noopener noreferrer"
            className="fixed lg:bottom-4 md:bottom-5 bottom-[5rem] right-4 z-50 bg-green-500 text-white p-3 rounded-full shadow-lg flex items-center justify-center hover:scale-105 transition-transform duration-300 animate-jump"
            style={{
              animation: "jump 1.5s infinite",
            }}
          >
            <FaWhatsapp size={24} />
          </a>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
