import Header from "@/Components/Header";
import Sidebar from "@/Components/Header/Sidebar";
import Footer from "@/Components/Footer";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="sm:flex flex-none">
          <Sidebar />
          <div className="sm:flex-1">
            {children} {/* This ensures that the page content renders here */}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
