import type { Metadata } from "next";

import "./globals.css";
import Header from "@/Components/Header";
import HomeBanner from "@/Components/HomeBanner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <HomeBanner />
        {children}
      </body>
    </html>
  );
}
